kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
  - name: foo-app
    image: arnobkumarsaha/learning_go:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    #args:
    #- "-text=foo"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  # Default port used by the image
  # targetPort will also be 5678
  - port: 8080 # 5678
    targetPort: 8080
---





kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  containers:
  - name: bar-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=bar"
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---






kind: Pod
apiVersion: v1
metadata:
  name: def-app
  labels:
    app: default
spec:
  containers:
  - name: def-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=def"
---
kind: Service
apiVersion: v1
metadata:
  name: def-service
spec:
  selector:
    app: default
  ports:
  # Default port used by the image
  - port: 5678
---






apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  #annotations: 
    #nginx.ingress.kubernetes.io/rewrite-target: "/"  # Added with /foo
spec:
  rules:
  - host: arnob.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: foo-service
            port:
              number: 8080 #5678
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: bar-service
            port:
              number: 5678
  defaultBackend:
    service:
      name: def-service
      port:
        number: 5678
---



