apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  # The default StorageClass is standard
  storageClassName: standard
  accessModes:
    # ReadOnlyMany & ReadWriteMany are not supported in hostPath pv
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
