apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage #it was 'standard', changed to become compatible with new-host-pv
  resources:
    requests: 
      storage: 1Gi
